name: Tech Heroes Inc.
favicon: null
layout_spectrum: 0.8435854457784444
typography_spectrum: 0.814931946573779
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#16191e'
    - '#0d5f6b'
    - '#bf9a87'
    - '#feeddf'
    - '#65d3f6'
  brandStrength: 0.3505129171535373
  lightness: 0.9130781698040664
  saturation: 0.7607657520566136
  rhythmicContrast: 0.7079543112777174
purpose: []
